### ISSUE TITLE
DRM 리무버가 정상 작동하는지 확인 부탁드립니다

### ISSUE THREAD

**Issue by myungsup1250** [disjukr/ridi-drm-remover#2]
우선 GUI까지 지원하는 리무버 툴 개발의 노고에 감사드립니다.
NODE.JS와 NPM을 처음 접해보는 관계로 겨우겨우 툴을 정상 작동시키는 것까지는 성공했습니다.
그런데 작업이 완료된 후에 새로 생긴 파일을 아무리 열어보려 해도 DRM이 해제되지 않은 것인지 파일을 여는 것 자체가 안됩니다...
disjukr 님께서 여유가 있으시다면 죄송스럽지만 drm remove 작업이 정상적으로 진행이 되는 것인지, 아니면 리디북스 차원에서 암호화 방식을 바꾼 것인지... 확인 부탁드려도 될까요?
감사합니다. 좋은 하루 되세요!

**Comment by teslamint** [comment]
제가 가진 pdf 전자책 2 권 중 하나만 해제가 되고(그것도 어도비 리더에선 못 읽고 맥의 프리뷰 앱 통해서만 열리네요) 다른 하나는 아예 읽지를 못하네요.

**Comment by nzgs** [comment]
해제 후 나온 인식되지 않는 .epub 파일의 확장자를 .zip으로 변경 후 PC에서 윈도우 반디집등으로 압축 해제한 다음, 나온 폴더를 압축률 0% 옵션 걸고 압축한 뒤 확장자를 다시 epub으로 바꾸면 정상적인 파일로 인식되네요.

drm 해제 자체에 문제가 있는 건 아닌 것 같습니다.

**Comment by noainred** [comment]
(node:920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Invalid key length
(node:920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

이런 에러가 뜨면서 안되네요.
어제까지 잘 되였는데, MACos 재설치하고나서부터 안되는 것인지... 뭐가 달라진 것인지..
부탁드립니다.
감사합니다.

**Comment by m73f74** [comment]
1. osx 버젼의 경우, 언제였는지 기억나지 않습니다만, 최근에 한 파일을 해보았더니 잘 되었습니다. 그러고 잊고 살았었지요... 그런데 오늘 새로 해보니 안 되네요...

2. node의 경우 npm install 까지는 성공(node v10으로는 안 되는 문제가 있어서 node v8로 해결)했습니다만, npm run start를 하면 아래의 에러와 함께 안됩니다.
npm run start

> ridi-drm-remover@0.0.1 start /Applications/ridi-drm-remover-v0.0.1-darwin-x64/temp/ridi-drm-remover-master/ridi-drm-remover-master
> yackage start

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/ridi-drm-remover-v0.0.1-darwin-x64/temp/ridi-drm-remover-master/ridi-drm-remover-master/yode/yode-v0.3.6-darwin-x64/yode ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ridi-drm-remover@0.0.1 start: `yackage start`
npm ERR! Exit status 1
npm ERR! 
[[ 하략 ]]

**Comment by osk2001** [comment]
맥용 2.4 버전 구할 수 있는 곳이 있나요. 광활한 인터넷의 바다에 맥용 2.4 버전이 없네요. 최신버전2.5.2는 암호화 처리 등이 변경되어 적용이 안됩니다.
